openapi: 3.0.0
servers:
  - url: //subdomain.adminolt.com/api
    description: Default server
info:
  description: |
    This is a sample server Petstore server.
    You can find out more about Swagger at
    [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).
    For this sample, you can use the api key `special-key` to test the authorization filters.
    # Introduction
    This API is documented
  version: 1.0.0
  title: Api AdminOLT
  termsOfService: 'https://adminolt.com/documentacion/terminos-y-condiciones-de-uso-5/'
  contact:
    name: API Support AdminOLT
    email: apiteam@adminolt.com
    url: https://adminolt.com/
  x-logo:
    url: 'https://admin.adminolt.com/static/img/logo.84639b0d929a.png'
    altText: AdminOLT logo
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
externalDocs:
  description: Find out how to create Github repo for your OpenAPI spec.
  url: 'https://github.com/Rebilly/generator-openapi-repo'
tags:
  - name: ONUs
    description: Everything about your ONUs
  - name: OLTs
    description: Everything about your OLTs
  - name: Zones
    description: Everything about your Zones
x-tagGroups:
  - name: ONU
    tags:
      - ONUs

  - name: OLT
    tags:
      - OLTs

  - name: System
    tags:
      - Zones
paths:
  /zones/:
    get:
      $ref: 'sistema/paths/zones/get.yaml'
    post:
      $ref: 'sistema/paths/zones/post.yaml'
  '/zones/{zone_id}/':
    get:
      $ref: 'sistema/paths/zones/detail_zone.yaml'
    put:
      $ref: 'sistema/paths/zones/put.yaml'
    delete:
      $ref: 'sistema/paths/zones/delete.yaml'
  /olt-list/:
    get:
      $ref: 'olt/paths/list_olts.yaml'
  /onu/unauthorized/:
    get:
      $ref: 'onu/paths/list_unauthorized_onu.yaml'
components:
  schemas:
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
    ZoneRequest:
      $ref: 'sistema/components/zones/zone_request.yaml'
    ZoneResponse:
      $ref: 'sistema/components/zones/zone_response.yaml'
    ZoneRequestUpdate:
      $ref: 'sistema/components/zones/zone_request_update.yaml'
    ZoneResponseUpdate:
      $ref: 'sistema/components/zones/zone_response_update.yaml'
    OLTRequest:
      $ref: 'olt/components/olt_request.yaml'
    OLTResponse:
      $ref: 'olt/components/olt_response.yaml'
    OnuUnauthorizedRequest:
      $ref: 'onu/components/list_unauthorized_onu_request.yaml'
    OnuUnauthorizedResponse:
      $ref: 'onu/components/list_unauthorized_onu_response.yaml'
  requestBodies:
    ZoneRequest:
      content:
        application/json:
          schema:
            allOf:
              - description: My Zone
                title: Zone
              - $ref: '#/components/schemas/ZoneRequest'
      description: Zone object that needs to be added to the system
      required: true
    ZoneRequestUpdate:
      content:
        application/json:
          schema:
            allOf:
              - description: My Zone
                title: Zone
              - $ref: '#/components/schemas/ZoneRequest'
      description: Zone object that needs to be update to the system
      required: true